version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dbt_postgres_db
    environment:
      POSTGRES_USER: db_user      
      POSTGRES_PASSWORD: db_password  
      POSTGRES_DB: shared_db   
    ports:
      - "5432:5432"               
    volumes:
      - db_data:/var/lib/postgresql/data

  dbt:
    image: dbt-postgres
    container_name: dbt_runner
    environment:
      DBT_PROFILES_DIR: /dbt/bdst_dbt
    volumes:
      - ./bdst_dbt:/dbt/bdst_dbt
    depends_on:
      - db
    command: tail -f /dev/null  # Запускает контейнер в режиме ожидания
    working_dir: /dbt/bdst_dbt

  superset:
    image: apache/superset
    container_name: superset
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_USER: admin
      SUPERSET_PASSWORD: admin
      SUPERSET_EMAIL: admin@example.com
    ports:
      - "8088:8088"   # Порт Superset для доступа
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    depends_on:
      - db
    

volumes:
  db_data:
