name: 'bdst_dbt'
version: '1.0'
config-version: 2

profile: 'bdst_dbt'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target"]
seed-paths: ["seeds"]

target-path: "target"

models:
  bdst_dbt:
    staging:
      materialized: table
