bdst_dbt:
  outputs:
    dev:
      type: postgres
      host: db
      user: db_user
      password: db_password
      port: 5432
      dbname: shared_db
      schema: dbt_schema  # Укажите отдельную схему для DBT
  target: dev
